### ISSUE TITLE
case class with default Option set to Some() is not correctly instanciated

### ISSUE THREAD

**Issue by ovarene** [andr83/scalaconfig#2]
A new test

```scala
 "Case class with default Option value to Some(...)" should "be correctly instanciated" in {
    val config = ConfigFactory.parseString(
      """
        |test = {
        |  key1 = value1
        |}
      """.stripMargin)
    case class Test(key1: String, key2: Option[Int] = Some(42) )
    val c = config.as[Test]("test")
    c.key1 should be ("value1")
    c.key2 should be (Some(42)) // the default value of the case class should be Some(42) and not None
  }
```
[info] - should be correctly instanciated *** FAILED ***
[info]   None was not equal to Some(42) (ReaderSpec.scala:239)

**Comment by andr83** [comment]
Thank you for informing about the problem. It's reproducing for any default values in case classes. Will try to resolve soon.

**Comment by andr83** [comment]
Fixed in 0.4-SNAPSHOT. But please pay attention - api was changed a little. Usage examples are in Readme file.

**Comment by ovarene** [comment]
Thanks a lot ! 👍  👍  👍 
When do you think this might become a NO SNAPSHOT fix ?
 I guess that the API change is not in favour of a quick change.

**Comment by andr83** [comment]
I hope it will on this week.
